# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\ntest.proto\"\x1f\n\x0esessionInquiry\x12\r\n\x05nonce\x18\x01 \x01(\x05\"#\n\rnewSessionNum\x12\x12\n\nsessionNum\x18\x01 \x01(\x05\"2\n\rappendRequest\x12\x12\n\nsessionNum\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\"\x1e\n\x0b\x61ppendReply\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\raddSeqRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0b\x61\x64\x64SeqReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8e\x01\n\x07Greeter\x12/\n\nnewSession\x12\x0f.sessionInquiry\x1a\x0e.newSessionNum\"\x00\x12(\n\x06\x61ppend\x12\x0e.appendRequest\x1a\x0c.appendReply\"\x00\x12(\n\x06\x61\x64\x64Seq\x12\x0e.addSeqRequest\x1a\x0c.addSeqReply\"\x00\x62\x06proto3')
)




_SESSIONINQUIRY = _descriptor.Descriptor(
  name='sessionInquiry',
  full_name='sessionInquiry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='sessionInquiry.nonce', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=45,
)


_NEWSESSIONNUM = _descriptor.Descriptor(
  name='newSessionNum',
  full_name='newSessionNum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionNum', full_name='newSessionNum.sessionNum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=82,
)


_APPENDREQUEST = _descriptor.Descriptor(
  name='appendRequest',
  full_name='appendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionNum', full_name='appendRequest.sessionNum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='appendRequest.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=134,
)


_APPENDREPLY = _descriptor.Descriptor(
  name='appendReply',
  full_name='appendReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='appendReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=166,
)


_ADDSEQREQUEST = _descriptor.Descriptor(
  name='addSeqRequest',
  full_name='addSeqRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='addSeqRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=200,
)


_ADDSEQREPLY = _descriptor.Descriptor(
  name='addSeqReply',
  full_name='addSeqReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='addSeqReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=232,
)

DESCRIPTOR.message_types_by_name['sessionInquiry'] = _SESSIONINQUIRY
DESCRIPTOR.message_types_by_name['newSessionNum'] = _NEWSESSIONNUM
DESCRIPTOR.message_types_by_name['appendRequest'] = _APPENDREQUEST
DESCRIPTOR.message_types_by_name['appendReply'] = _APPENDREPLY
DESCRIPTOR.message_types_by_name['addSeqRequest'] = _ADDSEQREQUEST
DESCRIPTOR.message_types_by_name['addSeqReply'] = _ADDSEQREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sessionInquiry = _reflection.GeneratedProtocolMessageType('sessionInquiry', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONINQUIRY,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:sessionInquiry)
  ))
_sym_db.RegisterMessage(sessionInquiry)

newSessionNum = _reflection.GeneratedProtocolMessageType('newSessionNum', (_message.Message,), dict(
  DESCRIPTOR = _NEWSESSIONNUM,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:newSessionNum)
  ))
_sym_db.RegisterMessage(newSessionNum)

appendRequest = _reflection.GeneratedProtocolMessageType('appendRequest', (_message.Message,), dict(
  DESCRIPTOR = _APPENDREQUEST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:appendRequest)
  ))
_sym_db.RegisterMessage(appendRequest)

appendReply = _reflection.GeneratedProtocolMessageType('appendReply', (_message.Message,), dict(
  DESCRIPTOR = _APPENDREPLY,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:appendReply)
  ))
_sym_db.RegisterMessage(appendReply)

addSeqRequest = _reflection.GeneratedProtocolMessageType('addSeqRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDSEQREQUEST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:addSeqRequest)
  ))
_sym_db.RegisterMessage(addSeqRequest)

addSeqReply = _reflection.GeneratedProtocolMessageType('addSeqReply', (_message.Message,), dict(
  DESCRIPTOR = _ADDSEQREPLY,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:addSeqReply)
  ))
_sym_db.RegisterMessage(addSeqReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='Greeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=235,
  serialized_end=377,
  methods=[
  _descriptor.MethodDescriptor(
    name='newSession',
    full_name='Greeter.newSession',
    index=0,
    containing_service=None,
    input_type=_SESSIONINQUIRY,
    output_type=_NEWSESSIONNUM,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='append',
    full_name='Greeter.append',
    index=1,
    containing_service=None,
    input_type=_APPENDREQUEST,
    output_type=_APPENDREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addSeq',
    full_name='Greeter.addSeq',
    index=2,
    containing_service=None,
    input_type=_ADDSEQREQUEST,
    output_type=_ADDSEQREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
